# Generated by Django 5.0.4 on 2024-04-23 18:27

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Link', 'Link'), ('File', 'File')], default='Link', max_length=20)),
                ('date_shared', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=portal.models.upload_to, verbose_name='File (PDF)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Link', 'Link'), ('File', 'File')], default='Link', max_length=20)),
                ('date_shared', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
