# Generated by Django 5.0.4 on 2024-04-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_fileresource_linkresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkresource',
            name='owner',
        ),
        migrations.DeleteModel(
            name='FileResource',
        ),
        migrations.DeleteModel(
            name='LinkResource',
        ),
    ]
