# Generated by Django 4.2.11 on 2024-05-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_options_message_file_message_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='photo',
        ),
    ]
